version: '3.8'

services:
  flaskapp:
    image: flasktest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ${PWD}/Scores.txt
        target: /app/Scores.txt
    ports:
      - "8777:3000"
