version: '3.8'

services:
  flaskapp:
    image: flasktest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/jenkins_home/workspace/Wog_flask/Scores.txt:/app/tmp/Scores.txt:ro
    ports:
      - "8777:3000"