version: '3'
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ronfeldman/flask_wog:latest
    environment:
      - MAC_WORKSPACE=${MAC_WORKSPACE}
    ports:
      - "8777:3000"
    volumes:
      - ${MAC_WORKSPACE}/Scores.txt:/app/Scores.txt
